name: easy_webrtc_server
description: Готовый WebSocket-сигналинг-сервер для WebRTC-звонков — управление комнатами и релей сообщений, на базе shelf.
version: 0.1.0
publish_to: 'none'
environment:
  sdk: ^3.13.0-103.1.beta

dependencies:
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6